#!/bin/bash
# simple line counter

cat << "EOF"
 _      _             _____                  _            
| |    (_)           / ____|                | |           
| |     _ _ __   ___| |     ___  _   _ _ __ | |_ ___ _ __ 
| |    | | '_ \ / _ \ |    / _ \| | | | '_ \| __/ _ \ '__|
| |____| | | | |  __/ |___| (_) | |_| | | | | ||  __/ |   
|______|_|_| |_|\___|\_____\___/ \__,_|_| |_|\__\___|_|   

EOF

echo A SIMPLE LINE COUNTER BY ALFREDO SEQUEIDA

echo enter the extension type of the files to count:

#read extensionType

find . -name '*.java' | xargs wc -l
